# Generated by Django 4.1.7 on 2023-03-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SongsLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(blank=True, default="", max_length=100)),
                ("artist", models.CharField(blank=True, default="", max_length=100)),
                ("added", models.CharField(blank=True, default="", max_length=100)),
            ],
        ),
    ]
