# Generated by Django 4.1.7 on 2023-03-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotly", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songslibrary",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
